python3 ./profile_function.py --min-cpus 0.25 --max-cpus 1.0  --cpus-step 0.25 --users 2 --function chameleon     --iat 1
python3 ./profile_function.py --min-cpus 0.5  --max-cpus 5.0  --cpus-step 0.5  --users 2 --function video_process --iat 1
python3 ./profile_function.py --min-cpus 1.0  --max-cpus 10.0 --cpus-step 1.0  --users 2 --function image_process --iat 1
python3 ./profile_function.py --min-cpus 0.5  --max-cpus 3.0  --cpus-step 0.5  --users 2 --function mobilenet     --iat 1
python3 ./profile_function.py --min-cpus 2.0  --max-cpus 32.0 --cpus-step 3.0  --users 2 --function linpack       --iat 1
python3 ./profile_function.py --min-cpus 2.0  --max-cpus 32.0 --cpus-step 3.0  --users 2 --function matmult       --iat 1
python3 ./profile_function.py --min-cpus 0.25 --max-cpus 1.0  --cpus-step 0.25 --users 2 --function pyaes         --iat 1
python3 ./profile_function.py --min-cpus 0.25 --max-cpus 1.0  --cpus-step 0.25 --users 2 --function float_op      --iat 1
python3 ./profile_function.py --min-cpus 0.5  --max-cpus 3.0  --cpus-step 0.5  --users 2 --function lr_review     --iat 1